### ISSUE TITLE
Installation error latest version of node-red-contrib-meshtastic 2.2.15-3

### ISSUE THREAD

**Issue by Kollensperger** [meshtastic/node-red-contrib-meshtastic#15]
A little unsure as to where the correct place to post this is, have also posted this error at https://github.com/scruplelesswizard/meshtastic-node-red/issues
Please feel free do delete if this is the wrong place.

Currently trying to install the updated  meshtastic-node-red via the palette or via pnpm throws the following error:

 ` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@buf%2Fmeshtastic_protobufs.bufbuild_es: Not Found - 404
This error happened while installing the dependencies of @meshtastic/meshtasticjs@2.2.15-1
@buf/meshtastic_protobufs.bufbuild_es is not in the npm registry, or you have no permission to fetch it.
No authorization header was set for the request.
Progress: resolved 4, reused 0, downloaded 3, added 0`

'@buf/meshtastic_protobufs.bufbuild_es@1.5.1-20231206215336-8002ce9b3c7a.1' is not in this registry.

**Comment by scruplelesswizard** [comment]
Thanks for the report @Kollensperger! This would be the best place to report issues with the `node-red-contrib-meshtastic` module.

There were some changes to the software we use to decode the Meshtastic packets that are not being correctly sourced. We are working on patching some of this in #14 and that release _may_ also solve the fetch issue. 

I don't recommend using versions `2.2.15-0` through `2.2.15-3` at this time, you can roll back to `1.0.2` following the [Installing with NPM](https://nodered.org/docs/user-guide/runtime/adding-nodes) instructions, or wait for `2.2.15-4` to be reviewed and released.

If you want to use `2.2.15-3` you can run the command `npm config set @buf:registry  https://buf.build/gen/npm/v1/` to tell `npm` where to fetch the Meshtastic protobuf definitions from
