### ISSUE TITLE
Updating to 2.2.17-1 version of node-red-contrib-meshtastic results in [@meshtastic/node-red-contrib-meshtastic/decode] TypeError: H.Mesh.Telemetry is not a constructor (line:2)

### ISSUE THREAD

**Issue by Kollensperger** [meshtastic/node-red-contrib-meshtastic#18]
also results in following message in node red web interface:
```
Flows stopped due to missing node types.

decode

```
restarting the node-red instance results in:

```
Welcome to Node-RED
===================

3 Jan 15:37:13 - [info] Node-RED version: v3.1.3
3 Jan 15:37:13 - [info] Node.js  version: v18.13.0
3 Jan 15:37:13 - [info] Linux 6.5.0-14-generic x64 LE
3 Jan 15:37:14 - [info] Loading palette nodes
3 Jan 15:37:16 - [info] Worldmap version 4.6.1
3 Jan 15:37:16 - [info] Node-RED Dashboard not found - ui_worldmap not installed.
3 Jan 15:37:17 - [warn] ------------------------------------------------------
3 Jan 15:37:17 - [warn] [@meshtastic/node-red-contrib-meshtastic/decode] TypeError: H.Mesh.Telemetry is not a constructor (line:2)
3 Jan 15:37:17 - [warn] ------------------------------------------------------
3 Jan 15:37:17 - [info] Settings file  : /root/.node-red/settings.js
3 Jan 15:37:17 - [info] Context store  : 'default' [module=memory]
3 Jan 15:37:17 - [info] User directory : /root/.node-red
3 Jan 15:37:17 - [info] Projects directory: /root/.node-red/projects

```

My attempt to downgrade gave an @ buf registry error. From Discord I saw the suggestion to run pnpm config set @buf:registry https://buf.build/gen/npm/v1 but I still haven't managed to return to version to 2.2.15-4 which I think was my last working version.

**Comment by Normanras** [comment]
Came here to submit the same issue as this just happened to me. My experience is that I drag the `decode` node onto the diagram and wherever I drop it the node is "frozen" in place and becomes unclickable. It is also frozen in that same place across my other diagram tabs which feels a bit more of a front-end problem. But in my palette, I have the same type error.
